#!/bin/bash
# ISRO LunaBot Demo - Full System Execution Script
# Run this after pressing Play in Isaac Sim

echo "═══════════════════════════════════════════════════════════════"
echo "🚀 ISRO LUNABOT CHALLENGE - FULL SYSTEM DEMONSTRATION"
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "⚠️  PREREQUISITES:"
echo "   1. Isaac Sim is running"
echo "   2. Play button has been pressed"
echo "   3. Nova Carter robot is loaded"
echo ""
echo "📸 Screenshots will be saved to: ~/lunabot_demo_captures/"
echo ""
echo "═══════════════════════════════════════════════════════════════"
echo "🎯 EXECUTION SEQUENCE (6 STEPS)"
echo "═══════════════════════════════════════════════════════════════"
echo ""

echo "STEP 1: Environmental Monitor"
echo "  - Monitors: Temperature, Pressure, Oxygen"
echo "  - Alerts on anomalies"
echo "  Command: ros2 run lunabot_maintenance env_monitor"
echo ""

echo "STEP 2: Scan Relay"
echo "  - Relays LiDAR data from /back_2d_lidar/scan to /scan"
echo "  - Enables sensor fusion"
echo "  Command: ros2 run lunabot_maintenance scan_relay"
echo ""

echo "STEP 3: SLAM Toolbox + Odometry Bridge"
echo "  - Real-time mapping"
echo "  - GPS-denied localization"
echo "  - Odometry fusion"
echo "  Command: ros2 launch slam_toolbox online_async_launch.py ..."
echo "  Command: ros2 run lunabot_maintenance slam_odom_bridge"
echo ""

echo "STEP 4: Static TF Publisher"
echo "  - Publishes map -> odom transform"
echo "  Command: ros2 run tf2_ros static_transform_publisher ..."
echo ""

echo "STEP 5: Nav2 Stack + RViz"
echo "  - Navigation system"
echo "  - Path planning"
echo "  - Visualization"
echo "  Command: ros2 launch nav2_bringup bringup_launch.py ..."
echo "  Command: ros2 run rviz2 rviz2 -d navigation.rviz"
echo ""

echo "STEP 6: Hazard Detection + Frontier Explorer"
echo "  - Autonomous exploration"
echo "  - Hazard detection with image capture"
echo "  - Control panel alerts"
echo "  Command: ros2 run lunabot_perception hazard_detector"
echo "  Command: ros2 run lunabot_perception control_panel"
echo "  Command: ros2 run lunabot_navigation frontier_explorer"
echo ""

echo "═══════════════════════════════════════════════════════════════"
echo "📸 CAPTURE POINTS FOR EACH STEP:"
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "1. Environmental Monitor: Terminal output showing telemetry"
echo "2. Scan Relay: Terminal showing scan relay active"
echo "3. SLAM: RViz showing map building in progress"
echo "4. Odometry: Terminal showing pose publishing"
echo "5. Nav2: RViz showing costmaps and paths"
echo "6. Hazard Detection: Captured hazard images with location"
echo "7. Frontier Explorer: RViz showing exploration progress"
echo "8. Control Panel: Alert log with hazard notifications"
echo ""

echo "═══════════════════════════════════════════════════════════════"
echo "🎬 READY TO START DEMONSTRATION"
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "Press Enter to begin Step 1 (Environmental Monitor)..."
