#!/bin/bash
# Hazard Detection System Commands

echo "🚨 HAZARD DETECTION & ANOMALY DETECTION SYSTEM"
echo "==============================================="
echo ""
echo "Run these in addition to the exploration system:"
echo ""

echo "Terminal 9 - Hazard Detector:"
echo "cd /home/aids/lunabot_ws && source /opt/ros/humble/setup.bash && source install/setup.bash && ros2 run lunabot_perception hazard_detector"
echo ""

echo "Terminal 10 - Control Panel (Alert Receiver):"
echo "cd /home/aids/lunabot_ws && source /opt/ros/humble/setup.bash && source install/setup.bash && ros2 run lunabot_perception control_panel"
echo ""

echo "==============================================="
echo "📋 FEATURES"
echo "==============================================="
echo "✅ Real-time obstacle detection using LiDAR"
echo "✅ Visual anomaly detection using camera"
echo "✅ Automatic image capture of hazards"
echo "✅ GPS location tagging"
echo "✅ Alert transmission to control panel"
echo "✅ Automatic path replanning on hazard detection"
echo ""

echo "==============================================="
echo "📁 OUTPUT LOCATIONS"
echo "==============================================="
echo "Hazard Images: ~/lunabot_hazards/"
echo "Alert Log: ~/lunabot_control_panel/hazard_log.txt"
echo ""

echo "==============================================="
echo "🔧 DIAGNOSTIC COMMANDS"
echo "==============================================="
echo "View hazard alerts:"
echo "ros2 topic echo /hazard_alerts"
echo ""
echo "Check detection status:"
echo "ros2 node info /hazard_detector"
echo ""
echo "View latest hazard images:"
echo "ls -lth ~/lunabot_hazards/ | head -10"
echo ""
echo "View alert log:"
echo "tail -f ~/lunabot_control_panel/hazard_log.txt"
echo ""

echo "==============================================="
echo "⚙️ HOW IT WORKS"
echo "==============================================="
echo "1. Robot patrols/explores using frontier explorer or autonomous patrol"
echo "2. Hazard detector monitors LiDAR and camera continuously"
echo "3. When hazard detected (obstacle <1.5m or visual anomaly):"
echo "   - Image captured and saved with annotations"
echo "   - Alert sent to control panel with location"
echo "   - Robot stops and Nav2 replans path around hazard"
echo "4. Control panel logs all alerts for operator review"
echo ""

echo "==============================================="
echo "🎯 DETECTION CRITERIA"
echo "==============================================="
echo "- Obstacle Detection: Objects within 1.5m in front cone"
echo "- Visual Anomaly: Unusual colors or high edge density"
echo "- Color Anomaly: >10% non-lunar surface colors"
echo "- Edge Density: >15% sharp edges (debris, equipment)"
echo ""
